name: Build .NET Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # usa a versão que queres

      - name: Restaurar dependências
        run: dotnet restore teste/teste.csproj

      - name: Compilar projecto
        run: dotnet build teste/teste.csproj --configuration Release --no-restore
