name: Build and Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura .NET Core no runner
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Restaura e faz o build do projeto .NET
      - name: Build .NET project
        run: |
          dotnet restore ./src/MyApp/MyApp.csproj  # Ajuste o caminho para o .csproj ou .sln
          dotnet build ./src/MyApp/MyApp.csproj --configuration Release  # Ajuste para o caminho correto

      # Publicação do projeto .NET
      - name: Publish .NET project
        run: |
          dotnet publish ./src/MyApp/MyApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp  # Ajuste para o caminho correto

      # Envio do artefato de build para o próximo job (deploy)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: myapp-artifact
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      # Baixar o artefato enviado do job anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: myapp-artifact

      # Login no Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'minhaweb-trl'
          slot-name: 'Production'
          package: './myapp'
