name: Build and Deploy ASP.NET Core App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite rodar manualmente pelo GitHub Actions UI

jobs:
  build:
    runs-on: windows-latest  # Usar uma máquina Windows para build .NET

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura .NET Core no runner
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      # Build do projeto .NET
      - name: Build .NET project
        run: |
          dotnet restore
          dotnet build --configuration Release

      # Publicação do projeto .NET
      - name: Publish .NET project
        run: |
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      # Envio do artefato de build para o próximo job (deploy)
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: myapp-artifact
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build  # Certifica-se de que o deploy só aconteça após o build

    environment:
      name: 'Production'

    steps:
      # Baixar o artefato enviado do job anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: myapp-artifact

      # Login no Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy para o Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'minhaweb-trl'  # Substitua pelo nome do seu Web App no Azure
          slot-name: 'Production'   # Pode ser 'Staging' ou outro slot, se necessário
          package: './myapp'  # Caminho do artefato gerado no build
